import {api} from '/app/js/api.js';
import {esc,ROLE_NAMES} from '/app/js/domain.js';
const dialog=document.createElement('dialog');dialog.className='pb-people-dialog';dialog.setAttribute('aria-labelledby','pbPeopleTitle');document.body.append(dialog);
const css=document.createElement('link');css.rel='stylesheet';css.href='/people/people.css';document.head.append(css);
let me=null,listing=null,requestId=0,previousFocus=null;
const labels=roles=>(roles||[]).map(x=>ROLE_NAMES[x]||x).join(' · ')||'Роль не назначена';
function screen(title,html){dialog.innerHTML=`<header class="pb-people-head"><h2 id="pbPeopleTitle">${esc(title)}</h2><button class="pb-people-close" data-people="close" aria-label="Закрыть">×</button></header><div class="pb-people-inner">${html}</div>`;if(!dialog.open){previousFocus=document.activeElement;dialog.showModal();}dialog.scrollTop=0;}
function close(){requestId++;dialog.close();previousFocus?.focus?.();}
function error(e){if([401,403].includes(e.status)){listing=null;screen('Доступ недоступен',`<p role="alert">${esc(e.message)}</p><p>Закройте приложение и откройте его заново через Telegram.</p>`);return;}const el=dialog.querySelector('[data-form-error]');if(el){el.textContent=e.message;el.hidden=false;}else screen('Не удалось загрузить',`<p role="alert">${esc(e.message)}</p><button class="pb-people-button" data-people="list">Повторить</button>`);}
async function openList(more=false){const ticket=++requestId;if(!more)screen('Сотрудники','<p role="status">Загружаем список…</p>');try{const data=await api('/people'+(more&&listing?.next?`?after=${listing.next}`:''));if(ticket!==requestId)return;listing=more?{...data,items:[...listing.items,...data.items]}:data;renderList();}catch(e){if(ticket===requestId)error(e);}}
function renderList(){screen('Сотрудники',`<div class="pb-people-actions"><button class="pb-people-button primary" data-people="add">+ Добавить сотрудника</button><button class="pb-people-button" data-people="documents">Документы</button></div><label>Найти сотрудника<input id="pbPeopleSearch" type="search" placeholder="Имя или Telegram ID"></label><p class="pb-people-muted">Можно назначить несколько ролей и отелей. Отключение доступа не удаляет рабочую историю.</p><div id="pbPeopleRows"></div>${listing.next?'<button class="pb-people-button" data-people="more">Загрузить ещё</button>':''}`);renderRows();}
function renderRows(){const q=(dialog.querySelector('#pbPeopleSearch')?.value||'').toLowerCase();dialog.querySelector('#pbPeopleRows').innerHTML=listing.items.filter(x=>`${x.name} ${x.telegramId}`.toLowerCase().includes(q)).map(x=>`<article class="pb-people-row"><div><strong>${esc(x.name)}</strong><small>${esc(labels(x.roles))}</small><small>ID ${esc(x.telegramId)} · ${x.active?'Доступ активен':'Доступ отключён'}</small></div>${x.editable?`<button class="pb-people-button" data-people-edit="${x.id}">Открыть</button>`:'<small>Защищённая запись</small>'}</article>`).join('')||'<p>Сотрудники не найдены.</p>';}
function form(id){const employee=id?listing.items.find(x=>x.id===id):null;if(id&&(!employee||!employee.editable))return;const roleOptions=['PHOTOGRAPHER','MANAGER',...(listing.canAssignAdmin?['ADMIN']:[])];screen(employee?'Карточка сотрудника':'Добавить сотрудника',`<form id="pbEmployeeForm" data-id="${employee?.id||''}"><label>Имя<input name="name" maxlength="150" value="${esc(employee?.name||'')}" required autocomplete="off"></label>${!employee?'<label>Telegram ID<input name="telegramId" inputmode="numeric" pattern="[0-9]+" required autocomplete="off"></label><p class="pb-people-muted">Сотрудник узнает ID командой /myid в боте. Имя пользователя @username не заменяет ID. После добавления ему нужно нажать /start.</p>':`<p class="pb-people-muted">Telegram ID: ${esc(employee.telegramId)}. Привязку аккаунта эта форма не меняет.</p>`}<fieldset><legend>Роли</legend>${roleOptions.map(r=>`<label><input type="checkbox" name="role" value="${r}" ${employee?.roles.includes(r)?'checked':''}>${esc(ROLE_NAMES[r]||r)}</label>`).join('')}</fieldset><fieldset><legend>Отели</legend>${listing.hotels.map(h=>`<label><input type="checkbox" name="hotel" value="${h.id}" ${employee?.hotelIds.includes(h.id)?'checked':''}>${esc(h.name)}</label>`).join('')||'<p>Сначала добавьте отель через существующее меню бота.</p>'}</fieldset>${employee?`<label><input type="checkbox" name="active" ${employee.active?'checked':''}>Рабочий доступ активен</label>`:''}<div class="pb-people-notice">Изменение ролей и отключение доступа записываются в аудит владельца. Эта форма не подписывает договор и не изменяет зарплату.</div><p class="pb-people-error" data-form-error hidden role="alert"></p><div class="pb-people-actions"><button class="pb-people-button primary" type="submit">Сохранить</button><button class="pb-people-button" type="button" data-people="list">Отмена</button></div></form>`);}
async function documents(){const ticket=++requestId;screen('Документы','<p role="status">Загружаем документы…</p>');try{const d=await api('/documents');if(ticket!==requestId)return;screen('Документы · проект',`<div class="pb-people-notice"><strong>Не подписано. Подписание отключено.</strong><p>Это проект для согласования, а не готовое оформление сотрудника.</p></div><article class="pb-people-rules">${esc(d.general)}</article><div class="pb-people-notice"><strong>Договор об оказании услуг</strong><p>${esc(d.servicesContract)}</p><strong>Персональные данные</strong><p>${esc(d.dataConsent)}</p></div><p class="pb-people-muted">Версия: ${esc(d.version)}. Документ не принят автоматически при открытии приложения.</p>${me?.permissions.manageSchedule?'<button class="pb-people-button" data-people="list">К сотрудникам</button>':''}`);}catch(e){if(ticket===requestId)error(e);}}
dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
dialog.addEventListener('input',e=>{if(e.target.id==='pbPeopleSearch')renderRows();});
dialog.addEventListener('click',e=>{const edit=e.target.closest('[data-people-edit]');if(edit)return form(Number(edit.dataset.peopleEdit));const action=e.target.closest('[data-people]')?.dataset.people;if(action==='close')close();if(action==='list')openList();if(action==='more')openList(true);if(action==='add')form();if(action==='documents')documents();});
dialog.addEventListener('submit',async e=>{if(e.target.id!=='pbEmployeeForm')return;e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]'),data=new FormData(f),id=Number(f.dataset.id)||null;const body={name:data.get('name'),roles:data.getAll('role'),hotelIds:data.getAll('hotel').map(Number)};if(!body.roles.length)return error(new Error('Выберите хотя бы одну роль.'));if(id){const old=listing.items.find(x=>x.id===id);body.active=data.has('active');body.revision=old.revision;}else body.telegramId=data.get('telegramId');b.disabled=true;try{await api('/people'+(id?`/${id}`:''),{method:id?'PUT':'POST',body});await openList();}catch(err){error(err);}finally{if(b.isConnected)b.disabled=false;}});
function inject(){if(!me)return;const top=document.querySelector('#topbar');if(!top?.children.length||top.querySelector('[data-open-people]'))return;const button=document.createElement('button');button.className='pb-people-trigger';button.dataset.openPeople='1';const editor=me.user.roles.some(r=>['OWNER','ADMIN'].includes(r));button.textContent=editor?'Сотрудники':'Документы';button.setAttribute('aria-label',editor?'Сотрудники и документы':'Документы приложения');button.addEventListener('click',()=>editor?openList():documents());top.append(button);}
async function boot(){try{me=await api('/me');inject();}catch{me=null;}}
const observer=new MutationObserver(()=>{if(me)inject();else if(document.querySelector('#topbar')?.children.length)boot();});observer.observe(document.querySelector('#topbar'),{childList:true});boot();
