import {api} from './api.js';
import {esc} from './domain.js';
import {openPractice} from './practice.js';
let track='photographer',data=null,development=null,currentSession=null,version=0,identity=null,planBusy=false,planError='';
const urls=new Set();
const quizDialog=document.createElement('dialog');quizDialog.className='practice-dialog';document.body.append(quizDialog);
const compareDialog=document.createElement('dialog');compareDialog.className='practice-dialog';document.body.append(compareDialog);
function changed(){document.dispatchEvent(new CustomEvent('pb-academy-coach-updated'));}
function message(text){const el=document.querySelector('#academyCoachStatus');if(el)el.textContent=text;}
function clearPhotos(){for(const u of urls)URL.revokeObjectURL(u);urls.clear();compareDialog.close();}
export function resetAcademyCoach(uid,roles=[]){if(identity!==uid){identity=uid;track=roles.includes('MANAGER')&&!roles.includes('PHOTOGRAPHER')?'booking':'photographer';data=null;development=null;currentSession=null;planBusy=false;planError='';version++;clearPhotos();quizDialog.close();}}
export function academyTrack(){return track;}
export async function loadAcademyCoach(selected=track){track=selected;const ticket=++version;planError='';let result;try{result=await api('/academy/coach?track='+track);}catch(error){if(error.status===401)throw error;result={error:error.message};}if(ticket!==version)return;data={skills:[],lessons:[],completed:[],comparison:[],scenarios:[],configured:false,stale:false,...result};
 if(track==='booking'){development=data._offline?{sessions:[]}:await api('/academy/development');if(ticket!==version)return;currentSession=development.sessions.find(s=>s.id===currentSession?.id)||development.sessions.find(s=>s.clientType.startsWith('booking-')&&s.status==='ACTIVE')||null;}
 if(data.stale&&data.configured&&!data._offline&&!planBusy)generatePlan(ticket);
}
async function generatePlan(ticket=version){planBusy=true;planError='';changed();try{const result=await api('/academy/coach/plan?track='+track,{method:'POST',body:{},timeoutMs:90000});if(ticket!==version)return;data.plan=result.plan;data.stale=false;}catch(error){if(ticket===version)planError=error.message;}finally{planBusy=false;changed();}}
export function academyTrackSwitch(){return `<div class="row wrap section" role="group" aria-label="Направление Академии"><button class="btn ${track==='photographer'?'primary':'ghost'}" data-coach-track="photographer">Фотограф</button><button class="btn ${track==='booking'?'primary':'ghost'}" data-coach-track="booking">Менеджер по записи</button>${track==='photographer'?'<button class="btn ghost" data-academy-tab="coach">AI-наставник и карта навыков</button>':''}</div>`;}
function skills(){return `<h2>Карта навыков</h2><p>Среднее по последним пяти оценкам каждого навыка. Практические работы и средние оценки AI-разборов съёмок учитываются отдельно; изменение — между первой и последней учтённой оценкой.</p><div class="coach-skills">${data.skills.map(s=>`<article class="academy-panel"><h3>${esc(s.label)}</h3><strong>${s.score===null?'Ещё нет оценки':s.score+'/100'}</strong>${s.score!==null?`<progress max="100" value="${s.score}" aria-label="${esc(s.label)}"></progress>`:''}<p>${s.delta!==null?`Изменение: ${s.delta>0?'+':''}${s.delta} п.п. · `:''}Оценок: ${s.samples}</p></article>`).join('')}</div>`;}
function planView(){const p=data.plan;return `<section class="academy-panel section"><span class="academy-kicker">AI НАЗНАЧАЕТ ЗАДАНИЕ</span><h2>${esc(p?.title||'Личный план развития')}</h2>${data.error?`<p role="alert">${esc(data.error)}</p>`:''}${data.diagnostic?'<p class="notice">Пока мало результатов. AI предложит диагностику; слабые места появятся после первой проверки.</p>':''}${planBusy?'<p role="status">AI готовит задание по вашим результатам…</p>':''}${planError?`<p role="alert">${esc(planError)}</p>`:''}${p?`<p>${esc(p.reason)}</p><ol>${p.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Критерии успеха</h3><ul>${p.successCriteria.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="row wrap">${p.lessonSlugs.map(slug=>`<button class="btn ghost" data-coach-lesson="${esc(slug)}">${esc(data.lessons.find(l=>l.slug===slug)?.title||slug)}</button>`).join('')}</div><button class="btn primary section" ${data.stale||!data.configured||data._offline?'disabled':''} ${track==='booking'?`data-coach-scenario="${esc(p.scenario)}"`:`data-coach-practice="${esc(p.category)}"`}>${track==='booking'?'Начать диалог с AI-гостем':'Выполнить практику из пяти кадров'}</button>`:''}${data.stale||!p?`<button class="btn ghost section" data-coach-plan ${planBusy||data._offline?'disabled':''}>${planBusy?'Готовим план…':'Повторить подготовку AI-задания'}</button>`:''}<p class="small">План обновляется после новых результатов. Просмотренные уроки и оценки сохраняются.</p></section>`;}
function trainingView(s){return `<section class="academy-panel section" id="bookingTraining"><h2>Разговор с AI-гостем</h2>${s.transcript.map(t=>`<article class="notice section"><strong>${t.role==='employee'?'Вы':t.role==='coach'?'AI-разбор':'Гость'}</strong><p>${esc(t.text)}</p></article>`).join('')}${s.status==='ACTIVE'?`<form id="bookingTrainingForm" class="form-grid"><label class="field">Ваш ответ<textarea class="input" name="text" maxlength="2000" rows="4"></textarea></label><div class="row wrap"><button class="btn primary" type="submit" value="reply">Ответить гостю</button><button class="btn ghost" type="submit" value="finish">Завершить и получить AI-разбор</button></div><p role="alert" data-booking-error></p></form>`:`<h3>Результат: ${s.evaluation.score}/100</h3>${s.evaluation.errors.map(x=>`<p>• ${esc(x)}</p>`).join('')}${s.evaluation.recommendations.map(x=>`<p>→ ${esc(x)}</p>`).join('')}`}</section>`;}
export function academyCoachScreen(){if(!data)return '<p>Загружаем Академию…</p>';return `<div class="academy-module"><h1>${track==='booking'?'Академия менеджера по записи':'AI-наставник фотографа'}</h1><p>${track==='booking'?'Знакомство → контакт → понятные условия → возражения → добровольная запись.':'Разбор фотографий → карта навыков → персональное задание → новая проверка.'}</p><p id="academyCoachStatus" role="status"></p>${data.canViewTeam?'<button class="btn ghost" data-coach-team>Прогресс команды и AI-задания</button><div id="academyCoachTeam"></div>':''}${data._offline?'<p class="notice">Без сети доступны сохранённые уроки и план. AI-разборы и отправка ответов требуют интернета.</p>':''}${!data.configured?'<p class="notice">AI-помощник сейчас не подключён. Доступны уроки и ранее сохранённые результаты.</p>':''}${planView()}${skills()}${track==='photographer'?`<section class="academy-panel section"><h2>До и после</h2><p>Исходные фотографии сохраняются при пересдаче. Можно сравнить кадры и оценки.</p>${data.comparison.length?'<button class="btn" data-coach-compare>Сравнить работы</button>':'<p>Сравнение появится после двух AI-разборов практики.</p>'}</section><section class="academy-panel section"><h2>Разобрать реальную съёмку</h2><p>Выберите загруженную съёмку: все её кадры проверит AI. Покупка фотографий для запуска разбора не требуется.</p><button class="btn" data-coach-shoots>Выбрать съёмку</button><div id="academyCoachShoots"></div><button class="btn ghost section" data-go="development">Сохранённые AI-разборы съёмок</button></section>`:`<section class="academy-panel section"><h2>Программа менеджера по записи</h2><p>Пройдено ${data.completed.length}/${data.lessons.length} уроков.</p>${data.lessons.map(l=>`<button class="menu-item" data-coach-lesson="${esc(l.slug)}"><span>${data.completed.includes(l.slug)?'✓':'○'}</span><span>${esc(l.title)}</span></button>`).join('')}<details><summary>Условия приглашения</summary><p>${esc(data.rules)}</p></details></section><section class="academy-panel section"><h2>Практика общения</h2><p>AI играет гостя и оценивает ваши ответы. Первое упражнение выбирается по личному плану; остальные сценарии доступны для повторения.</p><div class="row wrap">${data.scenarios.map(s=>`<button class="btn ghost" ${!data.configured||data._offline?'disabled':''} data-coach-scenario="${esc(s.type)}">${esc(s.title)}</button>`).join('')}</div>${currentSession?trainingView(currentSession):''}<h3>Мои диалоги</h3>${(development?.sessions||[]).filter(s=>s.clientType.startsWith('booking-')).map(s=>`<button class="btn ghost" data-coach-session="${s.id}">Диалог №${s.id} · ${s.status==='ACTIVE'?'В работе':s.evaluation.score+'/100'}</button>`).join('')}</section>`}</div>`;}
export async function openAcademyLesson(slug){const l=data?.lessons.find(x=>x.slug===slug);if(!l||l.locked)return;quizDialog.innerHTML=`<div class="practice-body"><button class="btn ghost" data-coach-close>Закрыть</button><h2>${esc(l.title)}</h2><div class="lesson-body">${esc(l.body)}</div><div id="academyQuiz"><p>Загружаем тест…</p></div></div>`;quizDialog.showModal();try{const result=await api(`/academy/coach/quizzes/${encodeURIComponent(slug)}`);quizDialog.querySelector('#academyQuiz').innerHTML=`<form id="academyLessonQuiz" data-slug="${esc(slug)}"><h3>Проверь понимание</h3>${result.questions.map((q,i)=>`<fieldset><legend>${esc(q.prompt)}</legend>${q.options.map((x,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${esc(x)}</label>`).join('')}</fieldset>`).join('')}<button class="btn primary section" type="submit">Проверить и сохранить урок</button><div role="status" data-quiz-result></div></form>`;}catch(error){quizDialog.querySelector('#academyQuiz').textContent=error.message;}}
async function comparison(){clearPhotos();compareDialog.innerHTML='<div class="practice-body"><button class="btn ghost" data-coach-compare-close>Закрыть</button><h2>До и после AI-проверки</h2><p>Разница оценок отражает проверенные работы; она сама по себе не доказывает причину изменения.</p><div class="coach-comparison">'+data.comparison.map((r,i)=>`<section><h3>${i===0?'Раньше':'Позже'} · ${r.score??'—'}/100</h3><p>Практика №${r.assignmentId}</p>${r.photos.map(p=>`<img data-coach-photo="${esc(p.url)}" alt="${i===0?'Исходный':'Новый'} кадр ${p.index}">`).join('')}</section>`).join('')+'</div></div>';compareDialog.showModal();const ticket=version;for(const img of compareDialog.querySelectorAll('[data-coach-photo]')){try{const blob=await api(img.dataset.coachPhoto,{responseType:'blob'});if(!compareDialog.open||ticket!==version)return;const u=URL.createObjectURL(blob);urls.add(u);img.src=u;}catch{img.alt+=' — фото недоступно';}}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-coach-track],[data-coach-plan],[data-coach-lesson],[data-coach-practice],[data-coach-scenario],[data-coach-session],[data-coach-compare],[data-coach-compare-close],[data-coach-close],[data-coach-shoots],[data-coach-shoot],[data-coach-team]');if(!b)return;b.disabled=true;try{
 if(b.dataset.coachTrack){clearPhotos();currentSession=null;await loadAcademyCoach(b.dataset.coachTrack);changed();return;}
 if(b.hasAttribute('data-coach-plan'))return await generatePlan();
 if(b.dataset.coachLesson)return await openAcademyLesson(b.dataset.coachLesson);
 if(b.dataset.coachPractice)return await openPractice(null,b.dataset.coachPractice);
 if(b.dataset.coachScenario){const active=development?.sessions.find(s=>s.clientType===b.dataset.coachScenario&&s.status==='ACTIVE');const result=active||await api('/academy/sales-training',{method:'POST',body:{clientType:b.dataset.coachScenario}});currentSession={id:result.id};await loadAcademyCoach();changed();document.querySelector('#bookingTraining')?.scrollIntoView({block:'start'});return;}
 if(b.dataset.coachSession){currentSession=development.sessions.find(s=>s.id===Number(b.dataset.coachSession));changed();return;}
 if(b.hasAttribute('data-coach-compare'))return await comparison();
 if(b.hasAttribute('data-coach-compare-close'))return clearPhotos();
 if(b.hasAttribute('data-coach-close'))return quizDialog.close();
 if(b.hasAttribute('data-coach-team')){const result=await api('/academy/coach/team');document.querySelector('#academyCoachTeam').innerHTML=result.items.map(u=>`<article class="academy-panel section"><h3>${esc(u.name)} · ${u.track==='booking'?'Менеджер по записи':'Фотограф'}</h3><p>Уроки: ${u.lessons}/${u.totalLessons} · Проверенных практик / диалогов: ${u.accepted} · Средняя оценка: ${u.quality??'—'}/100</p><p>${esc(u.focus||'AI-план пока не сформирован')}</p><p>${esc(u.reason||'')}</p></article>`).join('')||'<p>Сотрудников пока нет.</p>';return;}
 if(b.hasAttribute('data-coach-shoots')){const result=await api('/academy/coach/shoots');document.querySelector('#academyCoachShoots').innerHTML=result.shoots.map(s=>`<button class="menu-item" data-coach-shoot="${s.bookingId}">Запись №${s.bookingId} · ${esc(s.photographer)} · ${esc(s.date)} · ${s.total} кадров</button>`).join('')||'<p>Загруженных съёмок пока нет.</p>';return;}
 if(b.dataset.coachShoot){await api('/academy/coach/shoots',{method:'POST',body:{bookingId:Number(b.dataset.coachShoot)}});message('AI-разбор поставлен в очередь. Результат появится в сохранённых разборах.');}
 }catch(error){message(error.message);}finally{b.disabled=false;}});
document.addEventListener('submit',async e=>{if(!['academyLessonQuiz','bookingTrainingForm'].includes(e.target.id))return;e.preventDefault();const form=e.target,buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{
 if(form.id==='academyLessonQuiz'){const slug=form.dataset.slug;const answers=[...form.querySelectorAll('fieldset')].map((_,i)=>Number(new FormData(form).get('q'+i)));const result=await api(`/academy/coach/quizzes/${encodeURIComponent(slug)}`,{method:'POST',body:{answers}});form.querySelector('[data-quiz-result]').innerHTML=`<p>${result.score}/100 · ${result.passed?'Тест пройден':'Попробуйте снова'}</p>${result.feedback.map(f=>`<p>${f.correct?'✓':'→'} ${esc(f.explanation)}</p>`).join('')}`;if(result.passed){await api(`/academy/lessons/${encodeURIComponent(slug)}`,{method:'POST',body:{}});form.querySelector('[data-quiz-result]').insertAdjacentHTML('beforeend','<p>Урок сохранён.</p>');await loadAcademyCoach();document.dispatchEvent(new CustomEvent('pb-academy-lesson-completed'));}return;}
 const text=String(new FormData(form).get('text')||''),finish=e.submitter?.value==='finish';if(!finish&&!text.trim())throw Error('Напишите ответ гостю.');await api(`/academy/sales-training/${currentSession.id}/turn`,{method:'POST',body:{text,finish,revision:currentSession.revision},timeoutMs:90000});await loadAcademyCoach();changed();document.querySelector('#bookingTraining')?.scrollIntoView({block:'end'});
 }catch(error){const el=form.querySelector('[data-quiz-result],[data-booking-error]');if(el)el.textContent=error.message;}finally{buttons.forEach(b=>b.disabled=false);}});
compareDialog.addEventListener('close',()=>{for(const u of urls)URL.revokeObjectURL(u);urls.clear();});
