import {teamView,guideView,loadTeam,loadGuide,teamClick,teamSubmit} from './team.js';
import {insightsView,loadInsights,insightsClick} from './insights.js';
import {academyScreen,academyReference} from './academy.js';
import {openPractice} from './practice.js';
import {icon} from './icons.js';
import {esc,money,ROLE_NAMES,STATUS_NAMES,THEMES,defaultTheme,todayKey,addDays,dateLabel,initials} from './domain.js';
import {api} from './api.js';
import {initTelegram,applyTelegramTheme,haptic,openBot} from './telegram.js';
const tg=initTelegram(),$=s=>document.querySelector(s);
const state={me:null,dashboard:null,finance:null,schedule:null,academy:null,audit:null,bookings:[],route:'home',period:'today',day:todayKey(),week:todayKey(),academyTab:'home',search:'',requestId:0};
let toastTimer,focusBeforeDialog=null;
const request=api;
const NAV=[['home','home','Сегодня'],['shootings','camera','Съёмки'],['schedule','calendar','График'],['academy','cap','Академия'],['more','more','Ещё']];
const names={home:'Рабочий день',shootings:'Съёмки и записи',schedule:'График команды',academy:'Академия фотографа',more:'Ваше пространство',profile:'Мой профиль',finance:'Касса и начисления',audit:'Аудит действий',insights:'Контроль бизнеса',team:'Команда и HR',onboarding:'Начало работы'};
const roleNames=u=>(u.roles||[]).map(r=>ROLE_NAMES[r]||r).join(' · ');
const btn=(label,action,cls='primary',ic='')=>`<button class="btn ${cls}" data-action="${action}">${ic?icon(ic):''}${label}</button>`;
const empty=(title,text='',ic='list')=>`<div class="empty">${icon(ic)}<strong>${esc(title)}</strong>${esc(text)}</div>`;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function setTheme(theme){if(!THEMES.includes(theme))theme=defaultTheme(state.me.user.roles);document.documentElement.dataset.theme=theme;applyTelegramTheme(tg,theme);state.me.user.theme=theme;}
function side(route,i,label){return `<button class="side-item ${state.route===route?'active':''}" data-go="${route}">${icon(i)}${label}</button>`;}
function shell(){
 document.body.classList.toggle('academy-mode',state.route==='academy');const u=state.me.user,p=state.me.permissions;
 const brand=`<button class="brand-link" data-go="home" aria-label="Photo Boss, главная"><span class="brand-mark">${icon('camera')}</span><span><span class="brand-name">Photo<span>Boss</span></span><small class="brand-caption">WORKSPACE</small></span></button>`;
 $('#topbar').innerHTML=`${brand}<div class="desktop-only row muted small">${icon('pin')} Рабочее пространство Photo Boss</div><div class="row"><button class="icon-button" data-action="themes" aria-label="Выбрать оформление">${icon('palette')}</button><button class="avatar-btn" data-go="profile" aria-label="Мой профиль">${esc(initials(u.name))}</button></div>`;
 $('#bottomNav').innerHTML=NAV.map(([r,i,t])=>`<button class="nav-item ${state.route===r||(r==='more'&&['profile','finance','audit'].includes(state.route))?'active':''}" data-go="${r}" ${state.route===r?'aria-current="page"':''}>${icon(i)}<span>${t}</span></button>`).join('');
 $('#sidebar').innerHTML=`${brand}<div class="side-label">Рабочее пространство</div>${NAV.filter(x=>!['more','academy'].includes(x[0])).map(([r,i,t])=>side(r,i,t)).join('')}${side('finance','wallet',p.financeScope==='self'?'Мои начисления':'Касса и начисления')}<div class="side-label">Развитие</div>${side('academy','cap','Академия фотографа')}<div class="side-label">Управление</div>${p.audit?side('audit','shield','Аудит действий'):''}${side('profile','palette','Профиль и оформление')}<div class="side-bottom"><div class="notice">${icon('lock')} ${esc(roleNames(u))}<br>Доступ в соответствии с вашей ролью.</div></div>`;
 document.body.classList.add('protected');try{if(state.route==='home')tg?.BackButton?.hide();else tg?.BackButton?.show();}catch{}
}
function heading(title,subtitle='',action=''){return `<div class="page-head"><div><div class="eyebrow">${esc(dateLabel(state.me.today,{weekday:'short',day:'numeric',month:'long'}))} · Москва</div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${action}</div>`;}
function mark(status){const type=['STARTED','COMPLETED','SOLD','PAID'].includes(status)?'success':['READY_FOR_SALE','ASSIGNED','PARTIAL'].includes(status)?'warning':['REJECTED','CANCELLED'].includes(status)?'danger':'';return `<span class="badge ${type}">${esc(STATUS_NAMES[status]||{STARTED:'На смене',PLANNED:'По графику',ENDED:'Завершил',MISSING_CHECKOUT:'Нет отметки ухода',PAID:'Оплачено',PARTIAL:'Частично',UNPAID:'Не оплачено'}[status]||status)}</span>`;}
function watermark(){return `<div class="watermark">${esc(state.me.user.name)} · ID ${esc(state.me.user.telegramId)} · ${new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'}).format(new Date())}</div>`;}
function financeCard(f,full=false){
 if(!f)return empty('Данные недоступны','Попробуйте обновить страницу.','wallet');const self=f.scope==='self';
 return `<section class="cash-card" data-sensitive="true"><div class="cash-head"><span class="row">${icon('wallet')}${self?'Мои начисления':full?'Касса за период':'Общая касса сегодня'}</span><span class="badge">${esc(ROLE_NAMES[state.me.user.roles[0]])}</span></div><div class="cash-amount">${money(self?f.payroll:f.cashReceived)}</div><div class="cash-caption">${self?'Учтённые проценты, премии и удержания':'Подтверждённые поступления · не сумма всех продаж'}</div><div class="cash-bottom"><div><span>${self?'Мои продажи':'Продажи'}</span><strong>${money(f.sales)}</strong></div><div><span>${self?'Комиссия с продаж':'Начислено команде'}</span><strong>${money(self?f.employees.reduce((a,x)=>a+x.commission,0):f.payroll)}</strong></div></div>${watermark()}</section>`;
}
function employeeTable(f){
 if(!f.employees.length)return empty('Начислений пока нет','Здесь появятся учтённые комиссии, премии и удержания.','wallet');
 return `<div class="panel" data-sensitive="true"><div class="table-scroll"><table class="employee-table"><thead><tr><th>Сотрудник</th><th>Продажи</th><th>Начислено</th></tr></thead><tbody>${f.employees.map(x=>`<tr><td><button class="employee-button" data-employee="${x.id}"><span class="avatar small-avatar">${esc(initials(x.name))}</span><span><b>${esc(x.name.split(' ')[0])}</b><span class="role">${esc(ROLE_NAMES[x.role]||x.role)}</span></span></button></td><td>${money(x.sales)}</td><td><b class="accent">${money(x.earned)}</b></td></tr>`).join('')}</tbody></table></div><div class="table-note">Начислено — не означает выплачено. Нажмите на сотрудника для расчёта.</div></div>`;
}
function teamPerson(x){return `<div class="team-person avatar-colors"><div class="row"><span class="avatar">${esc(initials(x.name))}</span><div class="grow"><div class="name">${esc(x.name.split(' ')[0])}</div><div class="role">${esc(ROLE_NAMES[x.role]||x.role)}</div></div></div><div class="status-line">${mark(x.attendance||'PLANNED')}<span>${esc(x.start)}–${esc(x.end)}</span></div></div>`;}
function bookingCard(x){return `<button class="booking-row" data-booking="${x.id}"><div class="booking-time">${esc(x.time)}<small>${x.date===state.me.today?'сегодня':esc(dateLabel(x.date,{day:'numeric',month:'short'}))}</small></div><div class="grow"><div class="booking-name">${esc(x.client)}</div><div class="booking-meta">${esc(x.type)} · № ${esc(x.room)} · ${esc(x.hotel)}</div><div class="booking-footer">${mark(x.status)}<small>${esc(x.photographer?.split(' ')[0]||'Не назначен')}</small></div></div>${icon('chevron')}</button>`;}
function homeView(){
 const d=state.dashboard,p=state.me.permissions;const upcoming=d.bookings.filter(x=>!['COMPLETED','SOLD','REJECTED','CANCELLED','READY_FOR_SALE'].includes(x.status)).sort((a,b)=>a.time.localeCompare(b.time));const ready=d.bookings.filter(x=>x.status==='READY_FOR_SALE').length;
 const photoCount=d.team.filter(x=>x.role==='PHOTOGRAPHER').length,managerCount=d.team.filter(x=>x.role==='MANAGER').length;
 return `${heading('Всё под контролем',`${esc(state.me.user.name.split(' ')[0])}, вот ваш рабочий день.`,`<button class="icon-button" data-action="refresh" aria-label="Обновить данные">${icon('refresh')}</button>`)}
 <div class="team-overview"><div class="section-head"><span class="eyebrow">Команда сегодня</span><button class="text-button" data-go="schedule">График ${icon('arrow')}</button></div><div class="team-overview-people">${d.team.length?d.team.slice(0,6).map(x=>`<button data-go="schedule" class="team-chip"><span class="avatar small-avatar">${esc(initials(x.name))}</span><span class="team-chip-text"><b>${esc(x.name.split(' ')[0])}</b><small>${esc(ROLE_NAMES[x.role]||x.role)}</small></span><i class="dot ${x.attendance==='STARTED'?'positive':'muted'}"></i></button>`).join(''):'<span class="small muted">Смены ещё не назначены</span>'}</div></div>
 <div class="home-columns"><div>${financeCard(d.finance)}<div class="quick-actions">${p.manageBookings?btn('Новая запись','new-booking','primary','plus'):btn('Моя смена','shift','primary','clock')}${btn('Продажа','new-sale','','wallet')}</div>
 <div class="mini-metrics"><button class="mini-metric" data-go="shootings">${icon('camera')}<strong>${d.bookings.length}</strong><small>${p.financeScope==='self'?'Мои съёмки':'Съёмки сегодня'}</small></button><button class="mini-metric" data-action="ready">${icon('check')}<strong>${ready}</strong><small>Готовы к продаже</small></button><button class="mini-metric" data-go="schedule">${icon('users')}<strong>${d.team.filter(x=>x.attendance==='STARTED').length}</strong><small>Сейчас на смене</small></button></div>
 <section class="section"><div class="section-head"><h2>${p.financeScope==='self'?'Мой результат':'Продажи по сотрудникам'}</h2><button class="text-button" data-go="finance">Подробнее ${icon('arrow')}</button></div>${employeeTable(d.finance)}</section></div>
 <div><section class="section home-team-full"><div class="section-head"><div><h2>Команда сегодня</h2><p class="small">Фотографы: ${photoCount} · Менеджеры: ${managerCount}</p></div><button class="text-button" data-go="schedule">График ${icon('arrow')}</button></div><div class="team-strip">${d.team.length?d.team.map(teamPerson).join(''):empty('Нет смен на сегодня','','users')}</div></section>
 <section class="section"><div class="section-head"><h2>Очередь съёмок</h2><button class="text-button" data-go="shootings">Все ${icon('arrow')}</button></div><div class="stack">${upcoming.length?upcoming.slice(0,3).map(bookingCard).join(''):empty('Очередь пуста','Новые записи появятся здесь.','camera')}</div></section>
 <section class="section"><button class="academy-link" data-go="academy"><span class="academy-logo">${icon('cap')}</span><div><div class="eyebrow accent">PHOTO BOSS ACADEMY</div><h3>Академия фотографа</h3><p>Ваш отдельный мир роста и практики.</p></div>${icon('arrow')}</button></section></div></div>`;
}
function shootingsView(){const rows=state.bookings.filter(x=>(!state.onlyReady||x.status==='READY_FOR_SALE')&&(!state.search||`${x.client} ${x.room} ${x.photographer} ${x.id}`.toLowerCase().includes(state.search.toLowerCase()))).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));return `${heading('Съёмки и записи','Весь путь гостя — в одной карточке.',state.me.permissions.manageBookings?`<button class="icon-button accent-button" data-action="new-booking" aria-label="Новая запись">${icon('plus')}</button>`:'')}<div class="filter-row"><label class="field"><span>Дата съёмки</span><input id="bookingDay" type="date" class="input" value="${state.day}"></label><button class="btn small ghost" data-action="today-bookings">Сегодня</button>${state.onlyReady?`<button class="btn small" data-action="clear-ready">К продаже ×</button>`:''}</div><label class="searchbox">${icon('search')}<input id="bookingSearch" aria-label="Поиск съёмки" placeholder="Гость, номер комнаты, фотограф" value="${esc(state.search)}"></label><div id="bookingList" class="booking-list stack two-col">${rows.length?rows.map(bookingCard).join(''):empty('Съёмки не найдены','Измените дату или поисковый запрос.','camera')}</div>`;}
function scheduleView(){
 const data=state.schedule,days=Array.from({length:7},(_,i)=>addDays(state.week,i));const rows=data.items.filter(x=>x.date===state.day&&x.status!=='CANCELLED');
 return `${heading(state.me.permissions.manageSchedule?'График команды':'Мой график','Фотографы и менеджеры записи.',state.me.permissions.manageSchedule?`<button class="icon-button accent-button" data-action="new-shift" aria-label="Добавить смену">${icon('plus')}</button>`:'')}<div class="calendar-week-head"><button class="icon-button" data-week="-7" aria-label="Предыдущая неделя">‹</button><strong>${esc(dateLabel(days[0],{day:'numeric',month:'short'}))} — ${esc(dateLabel(days[6],{day:'numeric',month:'short'}))}</strong><button class="icon-button" data-week="7" aria-label="Следующая неделя">›</button></div><div class="calendar-strip">${days.map(d=>`<button class="day-button ${state.day===d?'selected':''}" data-day="${d}" aria-pressed="${state.day===d}"><small>${esc(dateLabel(d,{weekday:'short'}))}</small>${Number(d.slice(-2))}<span class="dot"></span></button>`).join('')}</div><div class="section-head"><h2>${esc(dateLabel(state.day))}</h2><button class="text-button" data-action="today-schedule">Сегодня</button></div><div class="panel">${rows.length?rows.map(s=>`<div class="schedule-person"><span class="avatar">${esc(initials(s.name))}</span><div><h3>${esc(s.name)}</h3><p class="small">${esc(ROLE_NAMES[s.role]||s.role)} · ${esc(s.hotel)}</p>${mark(s.attendance||s.status)}</div><div class="schedule-hours">${esc(s.start)}–${esc(s.end)}<small>${state.me.permissions.manageSchedule&&s.status==='PLANNED'&&s.attendance==='PLANNED'&&s.date>=state.me.today?`<button class="text-button negative" data-cancel-shift="${s.id}">Отменить</button>`:''}</small></div></div>`).join(''):empty('Выходной или смены не назначены','План и фактический выход на смену учитываются отдельно.','calendar')}</div><p class="compact-note">«По графику» — запланировано. «На смене» — подтверждён выход. План сам по себе не подтверждает присутствие.</p>`;
}
function financialView(){const f=state.finance,p=state.me.permissions;return `${heading(p.financeScope==='self'?'Мои деньги':'Касса и начисления',p.financeScope==='today'?'Администратору доступна общая касса только за сегодня.':'Продажи, поступления и начисления — отдельно.')}<div class="segmented">${(p.financeScope==='today'?['today']:p.financeScope==='all'?['today','week','month','custom']:['today','week','month']).map(x=>`<button data-period="${x}" class="${x===state.period?'active':''}">${{today:'Сегодня',week:'Неделя',month:'Месяц',custom:'Период'}[x]}</button>`).join('')}</div><div class="section stack-lg">${financeCard(f,true)}<div><div class="section-head"><h2>${f.scope==='self'?'Мой расчёт':'Разбивка по сотрудникам'}</h2><span class="small muted">${esc(dateLabel(f.from,{day:'numeric',month:'short'}))}–${esc(dateLabel(f.to,{day:'numeric',month:'short'}))}</span></div>${employeeTable(f)}</div><p class="financial-footnote">${esc(f.note||'Касса: подтверждённые чеки по времени подтверждения. Начисления — не фактические выплаты и не чистая прибыль.')}</p><section><div class="section-head"><h2>Продажи за период</h2>${btn('Добавить','new-sale','small','plus')}</div><div class="stack">${f.salesRows.length?f.salesRows.map(s=>`<div class="panel panel-pad"><div class="row between"><div class="grow"><h3>${esc(s.client||`Продажа №${s.id}`)}</h3><p class="small">${esc(s.employee)} · ${esc(dateLabel(s.date,{day:'numeric',month:'short'}))}</p></div><strong class="mono">${money(s.amount)}</strong></div>${mark(s.status)}</div>`).join(''):empty('Продаж пока нет','','wallet')}</div>${f.salesListLimited?`<p class="compact-note">Показаны последние 100 из ${f.salesCount} продаж. Итоги рассчитаны по всему периоду.</p>`:''}</section></div>`;}
function academyView(){return academyScreen(state.academy,state.me.user,state.academyTab,{preview:false});}
function themeChoices(){return `<div class="theme-grid">${[['premium','Премиум','Чёрный и золото'],['light','Светлая','Ясно и спокойно'],['photo','Фотостиль','Атмосфера кадра']].map(([id,n,desc])=>`<button class="theme-choice ${state.me.user.theme===id?'selected':''}" data-theme-choice="${id}" aria-pressed="${state.me.user.theme===id}"><div class="theme-mini ${id}"><span></span><span></span></div><strong>${n}</strong><small>${desc}</small></button>`).join('')}</div>`;}
function profileView(){const u=state.me.user;return `${heading('Мой профиль','Оформление меняется. Права доступа — нет.')}<div class="panel profile-card"><span class="avatar">${esc(initials(u.name))}</span><h2>${esc(u.name)}</h2><div class="row wrap">${u.roles.map(r=>`<span class="badge accent">${esc(ROLE_NAMES[r]||r)}</span>`).join('')}</div><div class="id">Telegram ID: ${esc(u.telegramId)}</div></div><section class="section"><div class="section-head"><h2>Ваш стиль</h2>${icon('palette','accent')}</div>${themeChoices()}<p class="compact-note">Выбор сохраняется в вашем аккаунте. На новом устройстве загрузится та же тема.</p></section><section class="section"><div class="notice">${icon('shield')} Общая касса за прошлые периоды и аудит — только владельцу. Тема не меняет вашу роль.</div><p class="compact-note">Ограничены копирование и печать, финансовые экраны подписаны вашим именем. Полный запрет скриншотов не гарантируется.</p></section>`;}
function moreView(){const p=state.me.permissions;const item=(r,ic,title,sub)=>`<button class="menu-item" data-go="${r}">${icon(ic)}<div class="grow"><strong>${title}</strong><small>${sub}</small></div>${icon('chevron')}</button>`;return `${heading('Ваше пространство','Всё остальное — под рукой.')}<div class="panel menu-list">${item('finance','wallet',p.financeScope==='self'?'Мои начисления':'Касса и начисления',p.financeScope==='all'?'Сегодня, неделя и месяц':p.financeScope==='today'?'Общая касса только за сегодня':'Только ваши продажи и деньги')}${item('schedule','calendar','График сотрудников','Смены фотографов и менеджеров')}${item('onboarding','cap','Начало работы','Инструкции по вашей роли и тест новичка')}${p.manageSchedule?item('team','list','Команда и HR','Кандидаты, дисциплина и развитие'):''}${p.audit?item('insights','wallet','Контроль бизнеса','KPI, сравнение периодов и события'):''}${p.audit?item('audit','shield','Аудит действий','Кто, что и когда изменил'):''}${item('profile','palette','Профиль и оформление','Три темы на ваш выбор')}</div><section class="section"><button class="academy-link" data-go="academy"><span class="academy-logo">${icon('cap')}</span><div><h3>Академия фотографа</h3><p>Курсы, практика, разборы, прогресс.</p></div>${icon('arrow')}</button></section>`;}
function auditView(){const a=state.audit;return `${heading('Аудит действий','Полная лента событий · только для владельца',`<span class="icon-button">${icon('shield','accent')}</span>`)}<div class="notice">Для старых записей показываются все имеющиеся сведения — отсутствующие детали не выдумываются.</div><div class="panel section">${a.items.length?a.items.map(x=>`<article class="audit-row"><div class="audit-time">${esc(new Date(x.at).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'}))}<br><small>${esc(new Date(x.at).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit'}))}</small></div><div class="grow"><h3>${esc(x.actor)}</h3><p>${esc(x.title)}</p><p>${esc(x.details||'')}</p><small>${esc(x.entity||'Событие')} ${x.entityId?'№'+esc(x.entityId):''} · ${esc(x.action)}</small></div></article>`).join(''):empty('Лента пока пуста','','shield')}</div>${a.next?`<div class="section">${btn('Загрузить ещё','more-audit','ghost')}</div>`:''}`;}
function render(){shell();const views={home:homeView,shootings:shootingsView,schedule:scheduleView,academy:academyView,more:moreView,profile:profileView,finance:financialView,audit:auditView,insights:insightsView,team:teamView,onboarding:guideView};$('#app').innerHTML=views[state.route]();}
async function loadRoute(route=state.route){
 if(!names[route])route='home';if(route==='audit'&&!state.me.permissions.audit){toast('Аудит доступен только владельцу.');route='home';}
 state.route=route;const ticket=++state.requestId;shell();$('#app').innerHTML='<div class="loading-screen"><div class="spinner"></div><p>Загружаем данные…</p></div>';
 try{
  if(route==='home'){const d=await request('/dashboard');if(ticket!==state.requestId)return;state.dashboard=d;state.me.today=d.today;}
  if(route==='finance'){const q=new URLSearchParams({period:state.period});if(state.period==='custom'){q.set('from',state.customFrom);q.set('to',state.customTo);}const d=await request(`/finance?${q}`);if(ticket!==state.requestId)return;state.finance=d;}
  if(route==='shootings'){const d=await request(`/bookings?day=${state.day}`);if(ticket!==state.requestId)return;state.bookings=d.items;}
  if(route==='schedule'){const d=await request(`/schedule?from=${state.week}&to=${addDays(state.week,6)}`);if(ticket!==state.requestId)return;state.schedule=d;}
  if(route==='academy'){const d=await request('/academy');if(ticket!==state.requestId)return;state.academy=d;}
  if(route==='team')await loadTeam();
  if(route==='onboarding')await loadGuide();
  if(route==='insights')await loadInsights();
  if(route==='audit'){const d=await request('/audit');if(ticket!==state.requestId)return;state.audit=d;}
  if(ticket!==state.requestId)return;render();
 }catch(e){if(ticket!==state.requestId)return;showError(e);}
}
function showError(error){const expired=error.status===401;if(expired){closeSheet();state.me=null;state.dashboard=null;state.finance=null;state.audit=null;$('#topbar').innerHTML='';$('#sidebar').innerHTML='';$('#bottomNav').innerHTML='';}$('#app').innerHTML=`<div class="loading-screen">${icon(expired?'lock':'refresh')}<h1>${expired?'Откройте через Telegram':'Не удалось загрузить'}</h1><p>${esc(error.message)}</p><p class="small">${expired?'Закройте приложение и откройте его кнопкой Photo Boss в боте.':'Рабочие данные не заменяются демонстрационными.'}</p><a class="btn primary" href="https://t.me/Really_Boss_bot">Открыть бота</a>${btn('Повторить','refresh','ghost','refresh')}</div>`;}
function go(route){closeSheet();history.replaceState(null,'',`#${route}`);haptic(tg);window.scrollTo({top:0,behavior:'instant'});return loadRoute(route);}
function showSheet(title,content){focusBeforeDialog=document.activeElement;$('#sheetContent').innerHTML=`<div class="eyebrow">PHOTO BOSS</div><h2 id="sheetTitle">${title}</h2>${content}`;if(!$('#sheet').open)$('#sheet').showModal();}
function closeSheet(){if($('#sheet').open){$('#sheet').close();focusBeforeDialog?.focus?.();}}
function field(label,html){return `<label class="field"><span>${label}</span>${html}</label>`;}
function formError(e){const el=$('#formError');if(el){el.hidden=false;el.textContent=e.message;}else toast(e.message);}
function handoff(action){const labels={'new-booking':['Новая запись','Оформление записи, фотограф и фото чека — в рабочем боте.'],'new-sale':['Регистрация продажи','Продажа и проверка оплаты проходят через рабочий процесс бота.'],'shift':['Моя смена','Отметка выхода с геолокацией и фотографией — в боте.']};const [title,text]=labels[action]||labels.shift;showSheet(title,`<p>${text}</p><div class="notice section">После перехода нажмите нужную кнопку в сообщении бота. Деньги в этом окне не списываются.</div><div class="section">${btn('Продолжить в боте',`handoff-${action}`,'primary full-width','arrow')}</div>`);}
function periodForm(){if(state.me.permissions.financeScope!=='all')return toast('Этот выбор доступен только владельцу.');showSheet('Период отчёта',`<form id="periodForm" class="form-grid"><div class="form-row">${field('С даты',`<input type="date" class="input" name="from" value="${state.customFrom||state.me.today.slice(0,8)+'01'}" max="${state.me.today}" required>`)}${field('По дату',`<input type="date" class="input" name="to" value="${state.customTo||state.me.today}" max="${state.me.today}" required>`)}</div><div class="notice">Даты включительно. Один отчёт — не более года.</div><p id="formError" class="form-error" hidden></p><button class="btn primary" type="submit">Показать отчёт</button></form>`);}
async function shiftForm(){const s=state.schedule||await request(`/schedule?from=${state.me.today}&to=${state.me.today}`);if(!s.employees.length||!s.hotels.length)return toast('Добавьте активных сотрудников и отель через бот.');showSheet('Назначить смену',`<form id="shiftForm" class="form-grid">${field('Сотрудник',`<select name="userId" class="input" required>${s.employees.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`)}${field('Отель',`<select name="hotelId" class="input" required>${s.hotels.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`)}${field('Дата',`<input class="input" type="date" name="date" value="${state.day}" min="${state.me.today}" required>`)}<div class="form-row">${field('Начало · Москва','<input type="time" name="start" class="input" value="09:00" required>')}${field('Окончание · Москва','<input type="time" name="end" class="input" value="19:00" required>')}</div><div class="notice">Пересекающиеся смены одного сотрудника не сохраняются. График не подтверждает присутствие.</div><p id="formError" class="form-error" hidden></p><button class="btn primary" type="submit">Назначить смену</button></form>`);}
function showBooking(id){const b=[...state.bookings,...(state.dashboard?.bookings||[])].find(x=>x.id===id);if(!b)return;showSheet(esc(b.client),`${mark(b.status)}<div class="detail-grid">${[['Запись',`№ ${b.id}`],['Когда',`${dateLabel(b.date)} · ${b.time}`],['Отель',b.hotel],['Номер',b.room],['Фотограф',b.photographer||'Не назначен'],['Кадров в съёмке',b.frames??'—']].map(([a,v])=>`<div class="detail"><small>${a}</small><b>${esc(v)}</b></div>`).join('')}</div><p class="small muted">Статусы меняются в рабочем процессе.</p><div class="section">${btn('Перейти к продаже','new-sale','primary full-width','wallet')}</div>`);}
function employeeDetail(id){const f=state.route==='finance'?state.finance:state.dashboard?.finance;const e=f?.employees.find(x=>x.id===id);if(!e)return;showSheet(esc(e.name),`<div class="detail-grid"><div class="detail"><small>Продажи</small><b>${money(e.sales)}</b></div><div class="detail"><small>Комиссия</small><b>${money(e.commission)}</b></div><div class="detail"><small>Премии и удержания</small><b>${money(e.adjustments)}</b></div><div class="detail"><small>Начислено</small><b>${money(e.earned)}</b></div></div><p class="small">Выплата и начисление — разные операции.</p>${watermark()}`);}
async function action(name){
 if(name==='close')return closeSheet();if(name==='refresh')return state.me?loadRoute():boot();
 if(name==='themes')return showSheet('Ваш стиль',`${themeChoices()}<p class="compact-note">Только оформление. Роль и доступ к деньгам не меняются.</p>`);
 if(name==='practice'){closeSheet();return openPractice();}
 if(['new-booking','new-sale','shift'].includes(name))return handoff(name);if(name==='new-shift')return shiftForm();
 if(name==='ready'){state.onlyReady=true;state.day=state.me.today;return go('shootings');}if(name==='clear-ready'){state.onlyReady=false;return render();}
 if(name==='today-bookings'){state.day=state.me.today;return loadRoute('shootings');}if(name==='today-schedule'){state.day=state.me.today;state.week=state.me.today;return loadRoute('schedule');}
 if(name==='more-audit'){const more=await request(`/audit?before=${state.audit.next}`);state.audit.items.push(...more.items);state.audit.next=more.next;return render();}
 if(name.startsWith('handoff-')){const result=await request('/handoff',{method:'POST',body:{action:name.slice(8)}});closeSheet();openBot(tg,result.url);}
}
document.addEventListener('click',async event=>{
 const b=event.target.closest('button');if(!b||b.disabled)return;
 try{
  if(b.dataset.team)return await teamClick(b);
  if(b.dataset.insight)return await insightsClick(b);
  if(b.dataset.go)return go(b.dataset.go);
  if(b.dataset.action){b.disabled=true;try{return await action(b.dataset.action);}finally{b.disabled=false;}}
  if(b.dataset.booking)return showBooking(Number(b.dataset.booking));if(b.dataset.employee)return employeeDetail(Number(b.dataset.employee));
  if(b.dataset.period==='custom')return periodForm();if(b.dataset.period){state.period=b.dataset.period;return loadRoute('finance');}
  if(b.dataset.day){state.day=b.dataset.day;return render();}if(b.dataset.week){state.week=addDays(state.week,Number(b.dataset.week));state.day=state.week;return loadRoute('schedule');}
  if(b.dataset.academyTab){state.academyTab=b.dataset.academyTab;render();document.querySelector('.academy-tabs')?.scrollIntoView({block:'start',behavior:'instant'});return;}
  if(b.dataset.practiceAssignment)return openPractice(Number(b.dataset.practiceAssignment));
  if(b.dataset.academyRef){const ref=academyReference(b.dataset.academyRef);if(!ref)return;return showSheet(esc(ref.title),`<img class="reference-photo" src="${ref.image}" alt="${esc(ref.title)}"><p class="reference-disclosure">Учебный референс Photo Boss, не работа сотрудника.</p><div class="lesson-body">${esc(ref.body)}</div><button class="btn primary full-width" data-action="practice">Перейти к практике</button>`);}
  if(b.dataset.academyInfo==='ai')return showSheet('ИИ-разбор',`<p>ИИ оценивает пять кадров по фокусу и технике, свету, композиции, позе, эмоции и разнообразию ракурсов. Проходной балл — 85 из 100. Слабые или повторяющиеся кадры отправляются на пересъёмку. При технической ошибке или сомнении проверка переходит владельцу.</p>`);
  if(b.dataset.themeChoice){const previous=state.me.user.theme,theme=b.dataset.themeChoice;setTheme(theme);b.disabled=true;try{await request('/preferences',{method:'PUT',body:{theme}});if($('#sheet').open)$('#sheetContent').innerHTML=`<div class="eyebrow">PHOTO BOSS</div><h2 id="sheetTitle">Ваш стиль</h2>${themeChoices()}<p class="compact-note">Тема сохранена для вашего профиля.</p>`;render();haptic(tg);}catch(e){setTheme(previous);throw e;}finally{b.disabled=false;}return;}
  if(b.dataset.lesson){const l=state.academy.lessons.find(x=>x.slug===b.dataset.lesson);if(!l||l.locked)return;return showSheet(`День ${l.day} · ${esc(l.title)}`,`<div class="lesson-body">${esc(l.body)}</div><button class="btn primary full-width" data-complete-lesson="${esc(l.slug)}">${state.academy.completed.includes(l.slug)?'Урок уже пройден':'Отметить изученным · +10 баллов'}</button>`);}
  if(b.dataset.completeLesson){b.disabled=true;await request(`/academy/lessons/${encodeURIComponent(b.dataset.completeLesson)}`,{method:'POST',body:{}});closeSheet();await loadRoute('academy');toast('Прогресс сохранён.');return;}
  if(b.dataset.cancelShift){const id=Number(b.dataset.cancelShift);showSheet('Отменить смену?',`<p>Изменение будет сохранено в графике и аудите. Начавшуюся смену отменить нельзя.</p><div class="section"><button class="btn primary full-width" data-confirm-cancel="${id}">Подтвердить отмену</button></div>`);return;}
  if(b.dataset.confirmCancel){b.disabled=true;await request(`/schedule/${Number(b.dataset.confirmCancel)}`,{method:'DELETE'});closeSheet();await loadRoute('schedule');toast('Смена отменена.');}
 }catch(e){b.disabled=false;if(e.status===401)showError(e);else toast(e.message);}
});
document.addEventListener('change',async e=>{if(e.target.id==='bookingDay'){if(!e.target.value)return;state.day=e.target.value;await loadRoute('shootings');}});
document.addEventListener('input',e=>{if(e.target.id==='bookingSearch'){state.search=e.target.value;const pos=e.target.selectionStart;$('#app').innerHTML=shootingsView();const input=$('#bookingSearch');input.focus();input.setSelectionRange(pos,pos);}});
document.addEventListener('submit',async e=>{
 if(['hrCreate','hrUpdate','hrHire','entryQuiz'].includes(e.target.id)){e.preventDefault();const b=e.target.querySelector('[type=submit],button:not([type])');b.disabled=true;try{await teamSubmit(e.target);}catch(err){toast(err.message);}finally{b.disabled=false;}return;}
 if(!['periodForm','shiftForm'].includes(e.target.id))return;e.preventDefault();const form=e.target,submit=form.querySelector('[type="submit"]');submit.disabled=true;
 try{const body=Object.fromEntries(new FormData(form));if(form.id==='periodForm'){if(body.from>body.to||body.to>state.me.today||(Date.parse(body.to)-Date.parse(body.from))/86400000>366)throw new Error('Проверьте даты: от начала к концу, не более года.');state.customFrom=body.from;state.customTo=body.to;state.period='custom';closeSheet();await loadRoute('finance');return;}await request('/schedule',{method:'POST',body});state.day=body.date;state.week=body.date;closeSheet();await loadRoute('schedule');toast('Смена сохранена.');}catch(err){submit.disabled=false;formError(err);}
});
$('#closeSheet').onclick=closeSheet;$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const r=$('#sheet').getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)closeSheet();}});
// UI deterrence only: this is not a guarantee against screenshots.
for(const event of ['copy','cut','contextmenu','dragstart'])document.addEventListener(event,e=>{if(!e.target.closest('input,textarea,[contenteditable]'))e.preventDefault();});
function privacy(active){$('#privacyScreen').hidden=active;}
document.addEventListener('visibilitychange',()=>privacy(!document.hidden));try{tg?.onEvent('deactivated',()=>privacy(false));tg?.onEvent('activated',()=>privacy(true));tg?.BackButton?.onClick(()=>go('home'));}catch{}
window.addEventListener('hashchange',()=>{if(state.me)loadRoute(location.hash.slice(1)||'home');});
async function boot(){try{state.me=await request('/me');await request('/session',{method:'POST',body:{}});state.period='today';state.day=state.me.today;state.week=state.me.today;state.dashboard=null;state.schedule=null;state.finance=null;state.academy=null;state.audit=null;state.bookings=[];state.onlyReady=false;state.search='';state.academyTab='home';setTheme(state.me.user.theme||defaultTheme(state.me.user.roles));await loadRoute(location.hash.slice(1)||'home');}catch(e){showError(e);}}
boot();

document.addEventListener('pb-practice-updated',()=>{if(state.me&&state.route==='academy')loadRoute('academy');});
