import {api} from './api.js';
import {esc,todayKey} from './domain.js';
import {enqueueBatch,enqueueOperation,outboxRows,retryOperation,flushOutbox} from './outbox.js';
let dialog=null,bookingId=null,album=null,objects=[],version=0,control=null,contacts=null;
const labels={shoot:'Нужно снять',sale:'Нужно продать',payment:'Проверить оплату',delivery:'Выдать фотографии'};
const date=value=>value?new Date(value+'Z').toLocaleString('ru-RU'):'Нет отметки';
function revoke(){for(const url of objects)URL.revokeObjectURL(url);objects=[];}
function shell(){if(dialog)return;dialog=document.createElement('dialog');dialog.className='sheet delivery-sheet';dialog.setAttribute('aria-label','Галерея выдачи');document.body.append(dialog);dialog.addEventListener('close',()=>{version++;revoke();});dialog.addEventListener('click',click);dialog.addEventListener('submit',submit);}
function message(text){const el=dialog?.querySelector('[data-delivery-status]');if(el)el.textContent=text;}
const queueLabels={local:'Сохранено на устройстве',syncing:'Отправляется',synced:'Сохранено на сервере',error:'Ошибка'};
async function render(){
 const queue=(await outboxRows()).filter(r=>r.kind.startsWith('delivery_')&&r.data.booking===bookingId),a=album;
 dialog.innerHTML=`<button class="icon-button close-sheet" data-delivery="close" aria-label="Закрыть">×</button><h2>Галерея съёмки №${bookingId}</h2><p>Фотограф: ${esc(a.photographer||'Не назначен')}</p>${a._offline?`<p class="notice">Сохранённые сведения от ${new Date(a._cachedAt).toLocaleString('ru-RU')}. Для просмотра серверных фото и выдачи нужна сеть. Новые фото можно сохранить в очередь.</p>`:''}<p data-delivery-status role="status" aria-live="polite"></p><button class="btn ghost" data-delivery="ai-review">AI-разбор этой съёмки</button>
 ${a.canEdit?`<form id="deliveryUploadForm" class="form-grid section"><label class="field"><span>Готовые фото для клиента, JPEG или PNG до 20 МБ</span><input class="input" name="photos" type="file" accept="image/jpeg,image/png" multiple required></label><label class="field"><span>Куда добавить</span><select class="input" name="target"><option value="all">Все фото</option><option value="selected">Все фото + «Выбранные»</option></select></label><button class="btn primary">Сохранить выбранные файлы</button></form>
 <form id="deliverySettingsForm" class="form-grid section"><label class="field"><span>Название альбома</span><input class="input" name="title" maxlength="120" value="${esc(a.title)}" required></label><label class="field"><span>Пароль ${a.passwordEnabled?'установлен':'не установлен'} (пустое поле сохраняет текущий)</span><input class="input" name="password" type="password" minlength="6" maxlength="100" autocomplete="new-password"></label>${a.passwordEnabled?'<label><input name="clearPassword" type="checkbox"> Убрать пароль</label>':''}<label class="field"><span>Срок доступа</span><select class="input" name="days"><option value="keep">Сохранить текущий срок</option><option value="7">7 дней с сегодняшнего дня</option><option value="30">30 дней</option><option value="90">90 дней</option><option value="0">Без ограничения</option></select></label><p class="small">Доступ до: ${a.expiresAt?date(a.expiresAt):'без ограничения'}</p><label class="field"><span>Что увидит гость</span><select class="input" name="deliveryMode"><option value="SELECTED" ${a.deliveryMode==='SELECTED'?'selected':''}>Только выбранные</option><option value="ALL" ${a.deliveryMode==='ALL'?'selected':''}>Все фото</option></select></label><label><input name="published" type="checkbox" ${a.published?'checked':''}> Открыть фотографии гостю</label><button class="btn">Сохранить настройки / создать ссылку гостя</button></form>`:''}
 <div class="delivery-grid">${a.photos.map(p=>`<figure><button class="btn ghost" data-delivery="view" data-photo="${p.id}"><img data-server-photo="${p.id}" alt="${esc(p.name)}" loading="lazy"><span>${esc(p.name)}</span></button>${a.canEdit?`<button class="btn ${p.selected?'primary':'ghost'}" data-delivery="select" data-photo="${p.id}">${p.selected?'Выбранное ✓':'Добавить в «Выбранные»'}</button>`:''}</figure>`).join('')||'<p>Фото ещё не загружены.</p>'}</div>
 ${a.published&&a.clientUrl?`<section class="section"><h3>QR-код Photo Boss</h3><img class="delivery-qr" alt="QR-код для клиента" data-delivery-qr><p class="small">Гость сканирует QR и сразу открывает Photo Boss в браузере. Telegram не нужен. Доступны только фотографии выбранного режима выдачи.</p><input class="input" readonly value="${esc(a.clientUrl)}" aria-label="Прямая ссылка Photo Boss"><button class="btn" data-delivery="copy-client">Скопировать прямую ссылку</button>${a.canEdit?'<button class="btn ghost" data-delivery="rotate">Заменить ссылку (старая перестанет работать)</button>':''}</section>`:''}
 <section class="section"><h3>Выдача</h3><p>Бот запущен: ${date(a.botStartedAt)}</p><p>Ссылка отправлена: ${date(a.botLinkSentAt)}</p><p>Запрос просмотра альбома: ${date(a.openedAt)}</p><p>Запрос скачивания: ${date(a.downloadedAt)}</p><p>Выдано сотрудником: ${date(a.handedAt)}</p>${a.canEdit?`<button class="btn" data-delivery="handoff">${a.handedAt?'Снять отметку выдачи':'Отметить выданным'}</button>`:''}</section>
 <section class="section"><h3>Очередь этой съёмки</h3>${queue.map(r=>`<p>${r.kind==='delivery_photo'?'Фото':'Выдача'} · ${esc(queueLabels[r.status])} ${esc(r.error||'')}${r.status==='error'?`<button class="btn small" data-delivery="retry" data-key="${esc(r.key)}">Повторить</button>`:''}</p>`).join('')||'<p>Нет операций.</p>'}<button class="btn ghost" data-delivery="refresh">Обновить</button><button class="btn ghost" data-delivery="sync">Синхронизировать</button></section>`;
 const ticket=version,bid=bookingId;
 if(a._offline)return;
 const jobs=a.photos.map(p=>async()=>{try{const blob=await api(`/delivery/${bid}/photos/${p.id}?preview=1`,{responseType:'blob'});if(ticket!==version)return;const url=URL.createObjectURL(blob);objects.push(url);const img=dialog.querySelector(`[data-server-photo="${p.id}"]`);if(img)img.src=url;}catch{const img=dialog.querySelector(`[data-server-photo="${p.id}"]`);if(img)img.alt='Фото пока недоступно';}});
 if(a.published&&a.clientUrl)jobs.push(async()=>{try{const blob=await api(`/delivery/${bid}/qr`,{responseType:'blob'});if(ticket!==version)return;const url=URL.createObjectURL(blob);objects.push(url);const img=dialog.querySelector('[data-delivery-qr]');if(img)img.src=url;}catch{message('QR-код недоступен. Можно скопировать прямую ссылку Photo Boss.')}});
 // Limit simultaneous image downloads and keep memory bounded to the current album.
 for(let i=0;i<jobs.length&&ticket===version;i+=4)await Promise.allSettled(jobs.slice(i,i+4).map(job=>job()));
}
export async function openDelivery(id){shell();const ticket=++version;bookingId=Number(id);revoke();dialog.innerHTML='<p role="status">Загружаем галерею…</p><button class="btn" data-delivery="close">Закрыть</button>';if(!dialog.open)dialog.showModal();try{const a=await api(`/delivery/${bookingId}`);if(ticket!==version)return;album=a;await render();}catch(e){if(ticket===version)dialog.innerHTML=`<p>${esc(e.message)}</p><button class="btn" data-delivery="close">Закрыть</button>`;}}
async function submit(e){if(!['deliveryUploadForm','deliverySettingsForm'].includes(e.target.id))return;e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;try{
 if(form.id==='deliveryUploadForm'){const files=[...form.elements.photos.files],selected=form.elements.target.value==='selected';if(!files.length)throw Error('Выберите фотографии.');for(const f of files)if(!['image/jpeg','image/png'].includes(f.type)||!f.size||f.size>20*1024*1024)throw Error('Нужны JPEG или PNG до 20 МБ.');await enqueueBatch(files.map(f=>({kind:'delivery_photo',date:todayKey(),data:{booking:bookingId,filename:f.name,selected},blob:f})));form.reset();message(`${files.length} фото сохранено в очередь. Они загрузятся пачкой.`);}
 else{const f=new FormData(form),body={title:f.get('title'),published:!!f.get('published'),deliveryMode:f.get('deliveryMode')};if(f.get('clearPassword'))body.password='';else if(f.get('password'))body.password=f.get('password');if(f.get('days')!=='keep')body.expiresDays=Number(f.get('days'));album=await api(`/delivery/${bookingId}`,{method:'POST',body});revoke();await render();message('Настройки сохранены.');}
 }catch(error){message(error.message)}finally{button.disabled=false;}}
async function click(e){const b=e.target.closest('[data-delivery]');if(!b)return;const kind=b.dataset.delivery;try{
 if(kind==='ai-review'){await api('/academy/coach/shoots',{method:'POST',body:{bookingId}});message('Все загруженные кадры съёмки поставлены в очередь AI-разбора. Результат — в Академии.');return;}
 if(kind==='close'){dialog.close();return;}
 if(kind.startsWith('copy-')){const value=album.clientUrl;try{await navigator.clipboard.writeText(value);message('Ссылка скопирована.')}catch{message('Скопируйте ссылку из поля.')}return;}
 if(kind==='view'){const bid=bookingId;const blob=await api(`/delivery/${bid}/photos/${b.dataset.photo}`,{responseType:'blob'});const url=URL.createObjectURL(blob);const viewer=document.createElement('dialog');viewer.className='delivery-viewer';const close=document.createElement('button');close.className='btn';close.textContent='Закрыть';close.onclick=()=>viewer.close();const full=document.createElement('img');full.src=url;full.alt=album.photos.find(p=>p.id===Number(b.dataset.photo))?.name||'Фотография';viewer.append(close,full);viewer.addEventListener('close',()=>{URL.revokeObjectURL(url);viewer.remove()});document.body.append(viewer);viewer.showModal();return;}
 if(kind==='select'){const photo=album.photos.find(p=>p.id===Number(b.dataset.photo));if(!photo)return;await api(`/delivery/${bookingId}/photos/${photo.id}/selected`,{method:'POST',body:{selected:!photo.selected}});album=await api(`/delivery/${bookingId}`);revoke();await render();message(photo.selected?'Убрано из «Выбранные».':'Добавлено в «Выбранные».');return;}
 if(kind==='handoff'){await enqueueOperation('delivery_handoff',todayKey(),{booking:bookingId,delivered:!album.handedAt});message('Отметка сохранена в очередь. Обновите после синхронизации.');return;}
 if(kind==='rotate'){if(!confirm('Заменить ссылку? Старые ссылки и QR-коды перестанут работать.'))return;album=await api(`/delivery/${bookingId}`,{method:'POST',body:{rotate:true}});revoke();await render();return;}
 if(kind==='retry')await retryOperation(b.dataset.key);if(kind==='sync')await flushOutbox();if(['refresh','sync','retry'].includes(kind))await openDelivery(bookingId);
 }catch(error){message(error.message)}}
export async function loadShootControl(){control=await api('/shoot-control');}
function controlCards(){const filter=document.querySelector('#shootControlFilter')?.value||'all',search=document.querySelector('#shootControlSearch')?.value.toLowerCase()||'';return control.items.filter(i=>(filter==='all'||i.tasks.includes(filter))&&`${i.client} ${i.hotel} ${i.room} ${i.photographer} ${i.id}`.toLowerCase().includes(search)).map(i=>`<article class="panel panel-pad"><h3>${esc(i.client)} · №${i.id}</h3><p>${esc(i.date)} ${esc(i.time)} · ${esc(i.hotel)} · комната ${esc(i.room)}</p><p>Фотограф: ${esc(i.photographer)}</p><p class="small">${i.guestConfirmed?"Гость подтвердил запись":"Нет подтверждения гостя"}${i.rescheduleRequested?" · Гость просит перенос":""}</p><div class="row wrap section">${i.cancelled?'<span class="badge">Отменена</span>':i.tasks.map(k=>`<span class="badge warning">${labels[k]}</span>`).join('')||'<span class="badge success">Завершена</span>'}</div><p class="small">Съёмка: ${i.shot?'готова':'ожидается'} · Продажа: ${i.sold?'зарегистрирована':'нет'} · Оплата: ${esc(i.paymentStatus||'нет продажи')} · Выдача: ${i.delivered?'отмечена':'нет отметки'}</p><p class="small">Запрос просмотра альбома: ${date(i.openedAt)}</p>${i.canGallery?`<button class="btn section" data-gallery-booking="${i.id}">Галерея выдачи</button>`:''}</article>`).join('')||'<p class="empty">Нет съёмок по выбранным условиям.</p>';}
const funnel=rows=>`<div class="table-scroll"><table class="employee-table"><thead><tr><th>Название</th><th>Записи</th><th>Снято</th><th>Продажи</th><th>Конверсия в продажу</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.booked}</td><td>${r.shot}</td><td>${r.sold}</td><td>${r.booked?Math.round(r.sold/r.booked*100)+'%':'—'}</td></tr>`).join('')}</tbody></table></div>`;
export function shootControlView(){return `<h1>Контроль съёмок</h1><p>Период: ${esc(control.from)} — ${esc(control.to)}. Задачи могут пересекаться.</p>${control._offline?`<p class="notice">Без сети: сохранённые сведения от ${new Date(control._cachedAt).toLocaleString('ru-RU')}.</p>`:''}<form id="shootControlPeriod" class="row wrap section"><label class="field"><span>С даты</span><input class="input" type="date" name="from" value="${esc(control.from)}" required></label><label class="field"><span>По дату</span><input class="input" type="date" name="to" value="${esc(control.to)}" required></label><button class="btn">Показать</button></form><p id="shootControlStatus" role="status"></p><div class="mini-metrics">${Object.entries(control.counts).map(([k,n])=>`<div class="mini-metric"><strong>${n}</strong><small>${labels[k]}</small></div>`).join('')}</div><div class="filter-row"><select id="shootControlFilter" class="input"><option value="all">Все</option>${Object.entries(labels).map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select><input id="shootControlSearch" class="input" placeholder="Гость, отель, комната, фотограф" aria-label="Поиск съёмки"></div><div id="shootControlCards" class="stack">${controlCards()}</div><details class="panel panel-pad section"><summary>Воронка по отелям</summary>${funnel(control.hotels)}</details><details class="panel panel-pad section"><summary>Воронка по фотографам</summary>${funnel(control.photographers)}</details><p class="small section">Количество приглашённых гостей пока не фиксируется; воронка начинается с записей. Оплата и начисления не меняются этим экраном.</p>`;}
export async function loadDeliveryContacts(){contacts=await api('/delivery-contacts');}
export function deliveryContactsView(){return `<h1>Контакты клиентов</h1><p>Всего: ${contacts.total}. Подписались на предложения: ${contacts.subscribers}.</p><div class="table-scroll panel section"><table class="employee-table"><thead><tr><th>Клиент</th><th>Telegram</th><th>Телефон</th><th>Предложения</th></tr></thead><tbody>${contacts.items.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.username||'—')}</td><td>${esc(c.phone||'Не предоставлен')}</td><td>${c.blocked?'Бот заблокирован':c.subscribed?'Подписан':'Не подписан'}</td></tr>`).join('')}</tbody></table></div><p class="small">Показаны последние ${contacts.items.length} контактов. Телефон сохраняется только по кнопке гостя. Отписка в боте: /stop.</p><form id="deliveryCampaignForm" class="form-grid section"><h2>Сообщение подписчикам</h2><label class="field"><span>Текст</span><textarea class="input" name="text" maxlength="3000" rows="5" required></textarea></label><label><input name="confirmed" type="checkbox" required> Отправить этот текст ${contacts.subscribers} подписчикам</label><button class="btn primary">Поставить рассылку в очередь</button><p id="deliveryCampaignStatus" role="status"></p></form><section class="section"><h2>История сообщений</h2>${contacts.campaigns.map(c=>`<article class="panel panel-pad section"><h3>Сообщение №${c.id}</h3><p>${esc(c.text)}</p><p>${esc(JSON.stringify(c.statuses))}</p></article>`).join('')||'<p>Рассылок пока нет.</p>'}</section>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-gallery-booking]');if(b)openDelivery(b.dataset.galleryBooking);});
for(const event of ['input','change'])document.addEventListener(event,e=>{if(['shootControlFilter','shootControlSearch'].includes(e.target.id))document.querySelector('#shootControlCards').innerHTML=controlCards();});
document.addEventListener('submit',async e=>{if(!['shootControlPeriod','deliveryCampaignForm'].includes(e.target.id))return;e.preventDefault();const form=e.target,button=form.querySelector('button'),f=new FormData(form);button.disabled=true;try{if(form.id==='shootControlPeriod'){control=await api('/shoot-control?'+new URLSearchParams(f));document.querySelector('#app').innerHTML=shootControlView();}else{const result=await api('/delivery-campaigns',{method:'POST',body:{text:f.get('text'),confirmed:!!f.get('confirmed')}});document.querySelector('#deliveryCampaignStatus').textContent=`В очереди: ${result.queued}. Повторно кнопку не нажимайте.`;form.reset();}}catch(error){const el=document.querySelector(form.id==='shootControlPeriod'?'#shootControlStatus':'#deliveryCampaignStatus');if(el)el.textContent=error.message;}finally{button.disabled=false;}});
