import {api} from './api.js';
import {esc,money} from './domain.js';
let report=null,events=[],period='week',from='',to='';
const labels={revenue:'Выручка',cash:'Подтверждённая касса',accrued:'Начислено сотрудникам',cashAfterAccruals:'Остаток после начислений',average:'Средний чек',sales:'Продажи',shootings:'Завершённые съёмки',bookings:'Записи',cancellations:'Отмены и отказы',late:'Опоздания',attendance:'Выходы на работу',employees:'Сотрудников на смене',receiptIssues:'Чеки для проверки'};
const monetary=new Set(['revenue','cash','accrued','cashAfterAccruals','average']);
export async function loadInsights(){const q=new URLSearchParams({period});if(period==='custom'){q.set('from',from);q.set('to',to);}report=await api('/insights?'+q);events=(await api('/events')).items;}
function value(k,v){return monetary.has(k)?money(v):esc(v);}
export function insightsView(){if(!report)return '';return `<h1>Контроль бизнеса</h1><p>${esc(report.from)} — ${esc(report.to)} · сравнение с ${esc(report.previous.from)} — ${esc(report.previous.to)}</p><div class="chips">${['today','week','month'].map((p,i)=>`<button class="chip" data-insight="period" data-period-value="${p}">${['Сегодня','Неделя','Месяц'][i]}</button>`).join('')}</div><div class="form-row section"><label class="field">С<input id="insightFrom" type="date" class="input" value="${report.from}"></label><label class="field">По<input id="insightTo" type="date" class="input" value="${report.to}"></label><button class="btn ghost" data-insight="custom">Сравнить</button></div><div class="kpi-grid section">${Object.entries(report.metrics).map(([k,v])=>`<article class="panel"><small>${esc(labels[k])}</small><h2>${value(k,v)}</h2><p>Изменение: ${value(k,report.changes[k].absolute)} · ${report.changes[k].percent===null?'нет базы для %':esc(report.changes[k].percent)+'%'}</p></article>`).join('')}</div><p class="notice">${esc(report.note)}</p><h2>Существенные изменения</h2>${report.flags.map(f=>`<article class="panel"><h3>${esc(labels[f.metric])}</h3><p>${esc(f.reason)}</p><p>${value(f.metric,f.previous)} → ${value(f.metric,f.current)}</p></article>`).join('')||'<p>Пороговые отклонения не обнаружены. Для малой выборки выводы не делаются.</p>'}<h2>Команда</h2>${report.employees.map(e=>`<article class="panel"><h3>${esc(e.name)}</h3><p>Продажи ${money(e.revenue)} · ${e.sales} продаж · ${e.bookings} записей · начислено ${money(e.accrued)}</p></article>`).join('')}<h2>Отели</h2>${report.hotels.map(h=>`<article class="panel"><h3>${esc(h.name)}</h3><p>Выручка ${money(h.revenue)} · касса ${money(h.cash)} · продаж ${h.sales}</p></article>`).join('')}<h2>Центр событий</h2><button class="btn primary" data-insight="scan">Проверить актуальные данные</button><p>Просмотр события не исправляет продажу и не подтверждает оплату.</p>${events.map(e=>`<article class="panel section"><small>${esc(e.priority)} · ${esc(e.at)} · ${e.resolved?'устранено':e.acknowledged?'просмотрено':'новое'}</small><h3>${esc(e.title)}</h3>${e.data.evidence?`<pre class="insight-evidence">${esc(JSON.stringify(e.data.evidence,null,2))}</pre>`:''}${e.data.entity?`<p>${esc(e.data.entity)} №${e.data.entityId}</p>`:''}${!e.acknowledged?`<button class="btn ghost" data-insight="ack" data-event-id="${e.id}">Отметить просмотренным</button>`:''}</article>`).join('')||'<p>Сохранённых событий пока нет.</p>'}`;}
export async function insightsClick(b){b.disabled=true;try{if(b.dataset.insight==='period')period=b.dataset.periodValue;if(b.dataset.insight==='custom'){period='custom';from=document.querySelector('#insightFrom').value;to=document.querySelector('#insightTo').value;}if(b.dataset.insight==='scan')await api('/events/scan',{method:'POST',body:{}});if(b.dataset.insight==='ack')await api(`/events/${b.dataset.eventId}/acknowledge`,{method:'POST',body:{}});await loadInsights();document.querySelector('#app').innerHTML=insightsView();}finally{b.disabled=false;}}
