import {api} from './api.js';
import {esc,money,ROLE_NAMES} from './domain.js';
import {enqueueOperation,outboxRows,retryOperation} from './outbox.js';
let day=null,queue=[];
export async function loadWorkday(){day=await api('/workday');queue=await outboxRows();}
const labels={local:'Сохранено локально',syncing:'Синхронизируется',synced:'Синхронизировано',error:'Ошибка'};
export function workdayView(){return `<h1>Итоги смены</h1><p>${esc(day.date)} · ${day.closed?'Смена закрыта':'Смена ещё не закрыта'}</p><div class="panel"><p>Записей ${day.summary.bookings} · отмен ${day.summary.cancelled} · продаж ${day.summary.sales}</p><h2>${money(day.summary.revenue)}</h2><p>Продаж без полной оплаты: ${day.summary.unpaid}</p></div><h2>Контрольные пункты</h2>${day.items.map(i=>`<article class="panel"><p>${esc(i.title)} · ${i.done?'выполнено':'не отмечено'}</p><button class="btn ghost" data-workday="check" data-key="${esc(i.key)}" data-done="${!i.done}">${i.done?'Снять отметку':'Готово'}</button>${day.canConfigure?`<button class="btn ghost" data-workday="disable" data-key="${esc(i.key)}">Отключить пункт</button>`:''}</article>`).join('')||'<p>Владелец и администратор могут добавить полезные для команды пункты. Автоматических обязательных отметок нет.</p>'}<form id="shiftNote" class="form-grid section"><label class="field">Что требует внимания? <textarea class="input" name="note" maxlength="2000" ${day.closed?'':'disabled'}>${esc(day.note)}</textarea></label><p>Цифры заполнены автоматически. Добавьте только неизвестные системе обстоятельства.</p><button class="btn primary" ${day.closed?'':'disabled'}>Сохранить замечание</button></form><h2>Отзывы гостей</h2>${day.sales.map(s=>`<p>Продажа №${s.id} · ${money(s.amount)} <button class="btn ghost" data-workday="feedback" data-id="${s.id}">Ссылка для оценки</button></p>`).join('')||'<p>Ссылки доступны после регистрации продажи.</p>'}${day.canConfigure?`<details class="panel section"><summary>Настроить чек-лист</summary><form id="checklistForm" class="form-grid"><label class="field">Полезный контрольный пункт<input class="input" name="title" required maxlength="200"></label>${['PHOTOGRAPHER','MANAGER','ADMIN','OWNER'].map(r=>`<label><input type="checkbox" name="roles" value="${r}">${esc(ROLE_NAMES[r])}</label>`).join('')}<button class="btn primary">Добавить</button></form></details>`:''}<h2>Синхронизация</h2><p>Локально сохраняются отметки чек-листа и замечания к закрытой смене. Продажи и подтверждение присутствия требуют сети.</p><div id="outboxList">${queueView()}</div>`;}
function queueView(){return queue.slice(-30).map(r=>`<article class="panel"><strong>${labels[r.status]}</strong><p>${r.kind==='checklist'?'Контрольный пункт':'Замечание к смене'} · ${esc(r.date)}</p>${r.error?`<p role="alert">${esc(r.error)}</p>`:''}${r.status==='error'?`<button class="btn ghost" data-workday="retry" data-key="${r.key}">Повторить</button>`:''}</article>`).join('')||'<p>Операций в очереди нет.</p>';}
export async function workdayClick(b){const a=b.dataset.workday;if(a==='check')await enqueueOperation('checklist',day.date,{itemKey:b.dataset.key,done:b.dataset.done==='true'});if(a==='retry')await retryOperation(b.dataset.key);if(a==='disable'){const i=day.items.find(i=>i.key===b.dataset.key);await api('/workday/checklist',{method:'PUT',body:{key:i.key,title:i.title,roles:i.roles,active:false}});await loadWorkday();}if(a==='feedback'){const r=await api(`/sales/${b.dataset.id}/feedback-link`,{method:'POST',body:{}});const box=document.createElement('div'),link=document.createElement('input');box.className='notice';link.className='input';link.readOnly=true;link.value=new URL(r.path,location.origin).href;box.append(document.createTextNode(r.note),link);b.parentNode.append(box);link.select();return;}queue=await outboxRows();document.querySelector('#app').innerHTML=workdayView();}
export async function workdaySubmit(form){const f=new FormData(form);if(form.id==='shiftNote')await enqueueOperation('shift_report',day.date,{note:f.get('note'),expectedSavedAt:day.reportSavedAt});if(form.id==='checklistForm'){await api('/workday/checklist',{method:'PUT',body:{key:'checklist:'+crypto.randomUUID(),title:f.get('title'),roles:f.getAll('roles'),active:true}});await loadWorkday();}queue=await outboxRows();document.querySelector('#app').innerHTML=workdayView();}
window.addEventListener('pb-outbox',async()=>{const el=document.querySelector('#outboxList');if(el){queue=await outboxRows();el.innerHTML=queueView();}});
